version: 1.0.{build}
build_script:
- cmd: >-
    dotnet restore --verbosity Debug

    dotnet build **\project.json
    
    dotnet pack -c release src/TvDbSharper/project.json
test_script:
- cmd: dotnet test test\TvDbSharper.Tests
